import 'package:book_story/enums/category_type.dart';
import 'package:book_story/models/book_model.dart';

class TempDB{
  static List<Book> bookList = <Book>[
    Book(
      id: 1,
      // imagePath: 'assets/books/age_4_plus/book1.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/1.png',
      title: '곰곰아, 괜찮아?',
      drawer: '김정민',
      writer: '김정민',
      bookPage: 32,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '02:17',
      favorite: 2739,
      rate: 4.5,
      playCount: 36082,
      description: '곰곰이는 책을 좋아해요. 걸어가면서도 책을 읽어요. 어느 날 곰곰이는 돌부리에 걸려 넘어졌어요. '
          '씽씽이를 타고 가던 콩콩이가 곰곰이에게 괜찮냐고 물어요. 그런데 곰곰이는 아무 말도 하지 않아요. 곰곰이는 정말 '
          '괜찮을까요? 책을 좋아하는 곰곰이와 곰곰이를 걱정하는 착한 친구들의 이야기를 담은 그림책, 『곰곰아, 괜찮아?』입니다.',
    ),
    Book(
      id: 2,
      // imagePath: 'assets/books/age_4_plus/book2.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/2.png',
      title: '나 아기 안할래',
      drawer: '김동영',
      writer: '김동영',
      bookPage: 34,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '04:44',
      favorite: 2739,
      rate: 4.5,
      playCount: 28953,
      description: '"착하기도 하지, 우리 아기 울지도 않고." '
          '엄마는 동생만 사랑하는 게 아닐까? 동생에게 엄마의 사랑을 빼앗겨 버렸다고 생각하는 양정이. 양정이는 동생 양양이처럼 기저귀를 '
          '차고, 유모차를 타고, 장난감이랑 책도 여기저기 마구 어질러 놓습니다. 과연 양정이는 어떤 마음일까요?',
    ),
    Book(
      id: 3,
      // imagePath: 'assets/books/age_4_plus/book3.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/3.png',
      title: '파란 물고기',
      drawer: '김릴리',
      writer: '차인우',
      bookPage: 36,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '04:11',
      favorite: 2739,
      rate: 4.5,
      playCount: 24393,
      description: '파란 물고기가 노란 물고기, 해마, 거북이, 문어, 아귀 등등 많은 친구들을 만나요. 그런데 자기와 통하는 친구를 '
          '만날 수 있을까요? 콜라주로 표현한 화려한 그림과 상징들을 통해 마음의 평온함을 느껴 보고 파란 물고기가 소통할 수 있는 '
          '친구를 만날 수 있는지 함께 떠나 볼까요?',
    ),
    Book(
        id: 4,
        // imagePath: 'assets/books/age_4_plus/book4.png',
        imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/4.png',
        title: '생각하는 ㄱㄴㄷ',
        drawer: 'Iwona Chmielewska',
        writer: 'Iwona Chmielewska',
        bookPage: 36,
        categoryAge: CategoryType.age4plus,
        categoryType: [CategoryType.fairyTale, CategoryType.creative],
        playTime: '08:30',
        favorite: 2739,
        rate: 4.5,
        playCount: 21480,
        description: '한글 낱자와 뛰어난 상상력의 만남! 재미있게 한글 공부도 하고, 상상력도 키우는 특별한 그림책! '
            '글자그림책 ㄱA1 시리즈는 ‘한글’과 ‘알파벳’과 ‘숫자’의 각 글자 형태와 의미에 사물을 연결시켜 풀어내는 '
            '독특한 상상력의 그림책입니다.'
    ),
    Book(
      id: 5,
      // imagePath: 'assets/books/age_4_plus/book5.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/5.png',
      title: '허수아비의 비밀',
      drawer: '이초혜',
      writer: '양승숙',
      bookPage: 48,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '07:27',
      favorite: 2739,
      rate: 4.5,
      playCount: 10244,
      description: '들판에서 참새를 지키던 허수아비가 무료한 나머지 그 동안 바라만 보던 산속으로 간다. '
          '숲 속의 모든 것이 신기하기만 한 허수아비는 온종일 숲 속을 돌아다니다가 피곤해 숲 속에서 잠이 든다. '
          '잠에서 깬 허수아비는 부랴부랴 들판으로 달려간다.',
    ),
    Book(
      id: 6,
      // imagePath: 'assets/books/popular/book1.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/6.png',
      title: '깨끗 공주와 깔끔 왕자',
      drawer: '김태란',
      writer: '이혜옥',
      bookPage: 28,
      categoryAge: CategoryType.upto6age,
      categoryType: [CategoryType.lifeStyle, CategoryType.habits],
      playTime: '06:59',
      favorite: 63427,
      rate: 4.5,
      playCount: 6342,
      description: '깨끗 공주와 깔끔 왕자',
    ),
    Book(
      id: 7,
      // imagePath: 'assets/books/popular/book2.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/7.png',
      title: '고요한 나라를 찾아서',
      drawer: '문지나',
      writer: '문지나',
      bookPage: 40,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '03:04',
      favorite: 58473,
      rate: 4.5,
      playCount: 5847,
      description: '고요한 나라를 찾아서',
    ),
    Book(
      id: 8,
      // imagePath: 'assets/books/popular/book3.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/8.png',
      title: '도시락 도둑',
      drawer: '김선배',
      writer: '정란희',
      bookPage: 40,
      categoryAge: CategoryType.age8plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '08:44',
      favorite: 55126,
      rate: 4.5,
      playCount: 5512,
      description: '도시락 도둑',
    ),
    Book(
      id: 9,
      // imagePath: 'assets/books/popular/book4.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/9.png',
      title: '치과의사 치카뿡',
      drawer: '윤공주',
      writer: '신선웅',
      bookPage: 26,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.natural, CategoryType.science],
      playTime: '08:07',
      favorite: 52940,
      rate: 4.5,
      playCount: 5294,
      description: '치과의사 치카뿡',
    ),
    Book(
      id: 10,
      // imagePath: 'assets/books/popular/book5.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/10.png',
      title: '인절미 시집가는 날',
      drawer: '김아인',
      writer: '김아인',
      bookPage: 40,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.society, CategoryType.culture],
      playTime: '08:24',
      favorite: 47542,
      rate: 4.5,
      playCount: 4754,
      description: '인절미 시집가는 날',
    ),
    Book(
      id: 11,
      // imagePath: 'assets/books/popular/book6.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/11.png',
      title: '고마워, 기역도깨비야',
      drawer: '조수진',
      writer: '조우상/이지수',
      bookPage: 34,
      categoryAge: CategoryType.upto6age,
      categoryType: [CategoryType.sophistication, CategoryType.learning],
      playTime: '05:02',
      favorite: 45671,
      rate: 4.5,
      playCount: 4567,
      description: '고마워, 기역도깨비야',
    ),
    Book(
      id: 12,
      // imagePath: 'assets/books/popular/book7.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/12.png',
      title: '올리와 바람',
      drawer: '로노조이 고시',
      writer: '로노조이 고시',
      bookPage: 40,
      categoryAge: CategoryType.upto6age,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '04:25',
      favorite: 42122,
      rate: 4.5,
      playCount: 4212,
      description: '올리와 바람',
    ),
    Book(
      id: 13,
      // imagePath: 'assets/books/popular/book8.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/13.png',
      title: '틀린게 아니라 다른거야',
      drawer: '유수정',
      writer: '최영미',
      bookPage: 38,
      categoryAge: CategoryType.age8plus,
      categoryType: [CategoryType.society, CategoryType.culture],
      playTime: '06:09',
      favorite: 40004,
      rate: 4.5,
      playCount: 4000,
      description: '틀린게 아니라 다른거야',
    ),
    Book(
      id: 14,
      // imagePath: 'assets/books/popular/book9.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/14.png',
      title: '공주양말',
      drawer: '윤샘',
      writer: '최서윤',
      bookPage: 28,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.lifeStyle, CategoryType.habits],
      playTime: '04:10',
      favorite: 34102,
      rate: 4.5,
      playCount: 3410,
      description: '공주양말',
    ),
    Book(
      id: 15,
      // imagePath: 'assets/books/popular/book10.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/15.png',
      title: '피가 붉다고?',
      drawer: '조수진',
      writer: '소망',
      bookPage: 26,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.natural, CategoryType.science],
      playTime: '03:45',
      favorite: 34879,
      rate: 4.5,
      playCount: 3487,
      description: '피가 붉다고?',
    ),
    Book(
      id: 16,
      // imagePath: 'assets/books/age_6_plus/book1.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/16.png',
      title: '내 마음대로',
      drawer: '김주현',
      writer: '이현',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '04:01',
      favorite: 2739,
      rate: 4.5,
      playCount: 43700,
      description: '내 마음대로',
    ),
    Book(
      id: 17,
      // imagePath: 'assets/books/age_6_plus/book2.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/17.png',
      title: '보송이의 작은 모험',
      drawer: '김규연',
      writer: '김규연',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '08:20',
      favorite: 2739,
      rate: 4.5,
      playCount: 33861,
      description: '보송이의 작은 모험',
    ),
    Book(
      id: 18,
      // imagePath: 'assets/books/age_6_plus/book3.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/18.png',
      title: '별나라에서 온 공주',
      drawer: '김재홍',
      writer: '김재홍',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '05:11',
      favorite: 2739,
      rate: 4.5,
      playCount: 32338,
      description: '별나라에서 온 공주',
    ),
    Book(
      id: 19,
      // imagePath: 'assets/books/age_6_plus/book4.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/19.png',
      title: '아빠 쉬는 날',
      drawer: '차야다',
      writer: '차야다',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: '05:21',
      favorite: 2739,
      rate: 4.5,
      playCount: 25078,
      description: '아빠 쉬는 날',
    ),
    Book(
      id: 20,
      // imagePath: 'assets/books/age_6_plus/book5.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/images/books/20.png',
      title: '솔비가 태어났어요',
      drawer: '이주윤',
      writer: '민수현',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.society, CategoryType.culture],
      playTime: '06:49',
      favorite: 2739,
      rate: 4.5,
      playCount: 12682,
      description: '솔비가 태어났어요',
    ),
  ];

  static List<Book> popularBookList = <Book>[

  ];
}