import 'package:book_story/enums/category_type.dart';
import 'package:book_story/models/book_model.dart';

class TempDB{
  static List<Book> bookList = <Book>[
    Book(
      bookId: 1,
      title: '곰곰아, 괜찮아?',
      drawer: '김정민',
      writer: '김정민',
      bookPage: 32,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 2 * 60 + 17,
      // imagePath: 'assets/books/age_4_plus/book1.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/1.png',
      bookDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/bookDescriptions/1.txt',
      writerDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/writerDescriptions/1.txt',
      publisherDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/publisherDescriptions/1.txt',
      // creationTime: DateTime.now(),
      // playCount: 36082,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 2,
      title: '나 아기 안할래',
      drawer: '김동영',
      writer: '김동영',
      bookPage: 34,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 4 * 60 + 44,
      // imagePath: 'assets/books/age_4_plus/book2.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/2.png',
      bookDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/bookDescriptions/2.txt',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 28953,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 3,
      title: '파란 물고기',
      drawer: '김릴리',
      writer: '차인우',
      bookPage: 36,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 4 * 60 + 11,
      // imagePath: 'assets/books/age_4_plus/book3.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/3.png',
      bookDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/bookDescriptions/3.txt',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 24393,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 4,
      title: '생각하는 ㄱㄴㄷ',
      drawer: 'Iwona Chmielewska',
      writer: 'Iwona Chmielewska',
      bookPage: 36,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 8 * 60 + 30,
      // imagePath: 'assets/books/age_4_plus/book4.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/4.png',
      bookDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/bookDescriptions/4.txt',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 21480,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 5,
      title: '허수아비의 비밀',
      drawer: '이초혜',
      writer: '양승숙',
      bookPage: 48,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 7 * 60 + 2,
      // imagePath: 'assets/books/age_4_plus/book5.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/5.png',
      bookDescriptionPath: 'https://d1uuv72cpfayuq.cloudfront.net/books/descriptions/bookDescriptions/5.txt',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 10244,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book( // TODO : 위 형식에 맞게 모두 변경하기 (데이터는 yes24에서 발췌하기)
      bookId: 6,
      title: '깨끗 공주와 깔끔 왕자',
      drawer: '김태란',
      writer: '이혜옥',
      bookPage: 28,
      categoryAge: CategoryType.upto6age,
      categoryType: [CategoryType.lifeStyle, CategoryType.habits],
      playTime: 6 * 60 + 59,
      // imagePath: 'assets/books/popular/book1.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/6.png',
      bookDescriptionPath: '깨끗 공주와 깔끔 왕자',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 6342,
      // favorite: 63427,
      // rate: 4.5,
    ),
    Book(
      bookId: 7,
      title: '고요한 나라를 찾아서',
      drawer: '문지나',
      writer: '문지나',
      bookPage: 40,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 3 * 60 + 4,
      // imagePath: 'assets/books/popular/book2.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/7.png',
      bookDescriptionPath: '고요한 나라를 찾아서',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 5847,
      // favorite: 58473,
      // rate: 4.5,
    ),
    Book(
      bookId: 8,
      title: '도시락 도둑',
      drawer: '김선배',
      writer: '정란희',
      bookPage: 40,
      categoryAge: CategoryType.age8plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 8 * 60 + 44,
      // imagePath: 'assets/books/popular/book3.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/8.png',
      bookDescriptionPath: '도시락 도둑',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 5512,
      // favorite: 55126,
      // rate: 4.5,
    ),
    Book(
      bookId: 9,
      title: '치과의사 치카뿡',
      drawer: '윤공주',
      writer: '신선웅',
      bookPage: 26,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.natural, CategoryType.science],
      playTime: 8 * 60 + 7,
      // imagePath: 'assets/books/popular/book4.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/9.png',
      bookDescriptionPath: '치과의사 치카뿡',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 5294,
      // favorite: 52940,
      // rate: 4.5,
    ),
    Book(
      bookId: 10,
      title: '인절미 시집가는 날',
      drawer: '김아인',
      writer: '김아인',
      bookPage: 40,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.society, CategoryType.culture],
      playTime: 8 * 60 + 24,
      // imagePath: 'assets/books/popular/book5.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/10.png',
      bookDescriptionPath: '인절미 시집가는 날',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 4754,
      // favorite: 47542,
      // rate: 4.5,
    ),
    Book(
      bookId: 11,
      title: '고마워, 기역도깨비야',
      drawer: '조수진',
      writer: '조우상/이지수',
      bookPage: 34,
      categoryAge: CategoryType.upto6age,
      categoryType: [CategoryType.sophistication, CategoryType.learning],
      playTime: 5 * 60 + 2,
      // imagePath: 'assets/books/popular/book6.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/11.png',
      bookDescriptionPath: '고마워, 기역도깨비야',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 4567,
      // favorite: 45671,
      // rate: 4.5,
    ),
    Book(
      bookId: 12,
      title: '올리와 바람',
      drawer: '로노조이 고시',
      writer: '로노조이 고시',
      bookPage: 40,
      categoryAge: CategoryType.upto6age,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 4 * 60 + 25,
      // imagePath: 'assets/books/popular/book7.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/12.png',
      bookDescriptionPath: '올리와 바람',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 4212,
      // favorite: 42122,
      // rate: 4.5,
    ),
    Book(
      bookId: 13,
      title: '틀린게 아니라 다른거야',
      drawer: '유수정',
      writer: '최영미',
      bookPage: 38,
      categoryAge: CategoryType.age8plus,
      categoryType: [CategoryType.society, CategoryType.culture],
      playTime: 6 * 60 + 9,
      // imagePath: 'assets/books/popular/book8.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/13.png',
      bookDescriptionPath: '틀린게 아니라 다른거야',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 4000,
      // favorite: 40004,
      // rate: 4.5,
    ),
    Book(
      bookId: 14,
      title: '공주양말',
      drawer: '윤샘',
      writer: '최서윤',
      bookPage: 28,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.lifeStyle, CategoryType.habits],
      playTime: 4 * 60 + 10,
      // imagePath: 'assets/books/popular/book9.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/14.png',
      bookDescriptionPath: '공주양말',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 3410,
      // favorite: 34102,
      // rate: 4.5,
    ),
    Book(
      bookId: 15,
      title: '피가 붉다고?',
      drawer: '조수진',
      writer: '소망',
      bookPage: 26,
      categoryAge: CategoryType.age4plus,
      categoryType: [CategoryType.natural, CategoryType.science],
      playTime: 3 * 60 + 45,
      // imagePath: 'assets/books/popular/book10.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/15.png',
      bookDescriptionPath: '피가 붉다고?',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 3487,
      // favorite: 34879,
      // rate: 4.5,
    ),
    Book(
      bookId: 16,
      title: '내 마음대로',
      drawer: '김주현',
      writer: '이현',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 4 * 60 + 1,
      // imagePath: 'assets/books/age_6_plus/book1.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/16.png',
      bookDescriptionPath: '내 마음대로',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 43700,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 17,
      title: '보송이의 작은 모험',
      drawer: '김규연',
      writer: '김규연',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 8 * 60 + 20,
      // imagePath: 'assets/books/age_6_plus/book2.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/17.png',
      bookDescriptionPath: '보송이의 작은 모험',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 33861,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 18,
      title: '별나라에서 온 공주',
      drawer: '김재홍',
      writer: '김재홍',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 5 * 60 + 11,
      // imagePath: 'assets/books/age_6_plus/book3.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/18.png',
      bookDescriptionPath: '별나라에서 온 공주',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 32338,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 19,
      title: '아빠 쉬는 날',
      drawer: '차야다',
      writer: '차야다',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.fairyTale, CategoryType.creative],
      playTime: 5 * 60 + 21,
      // imagePath: 'assets/books/age_6_plus/book4.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/19.png',
      bookDescriptionPath: '아빠 쉬는 날',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 25078,
      // favorite: 2739,
      // rate: 4.5,
    ),
    Book(
      bookId: 20,
      title: '솔비가 태어났어요',
      drawer: '이주윤',
      writer: '민수현',
      bookPage: 36,
      categoryAge: CategoryType.age6plus,
      categoryType: [CategoryType.society, CategoryType.culture],
      playTime: 6 * 60 + 49,
      // imagePath: 'assets/books/age_6_plus/book5.png',
      imagePath: 'https://d1uuv72cpfayuq.cloudfront.net/books/images/20.png',
      bookDescriptionPath: '솔비가 태어났어요',
      writerDescriptionPath: '',
      publisherDescriptionPath: '',
      // creationTime: DateTime.now(),
      // playCount: 12682,
      // favorite: 2739,
      // rate: 4.5,
    ),
  ];
}